// Auto-generated sprite labels for UI display
// Generated from sprite-metadata.json on 2025-11-27

export const spriteLabels = {
  "1_Blemish_Skin": {
    "blemish_00_00.png": "Single Scar Black",
    "blemish_01_00.png": "Double Scars Black",
    "blemish_02_00.png": "Vertical Scar Black"
  },
  "2_Nose_Skin": {
    "nose_00_00.png": "Rounded Curved Feminine",
    "nose_00_01.png": "Rounded Curved Feminine",
    "nose_00_02.png": "Rounded Curved Feminine",
    "nose_01_00.png": "Broad Curved Neutral",
    "nose_01_01.png": "Broad Curved Neutral",
    "nose_02_00.png": "Angular Masculine",
    "nose_03_00.png": "Button Nose Cute",
    "nose_04_00.png": "Hook Nose Prominent",
    "nose_04_01.png": "Hook Nose Prominent",
    "nose_05_00.png": "Straight Narrow Refined",
    "nose_05_01.png": "Straight Narrow Refined",
    "nose_06_00.png": "Short Rounded Compact",
    "nose_06_01.png": "Short Rounded Compact",
    "nose_07_00.png": "Upturned Perky",
    "nose_07_01.png": "Upturned Perky",
    "nose_08_00.png": "Curved Compact Subtle",
    "nose_08_01.png": "Curved Compact Neat",
    "nose_09_00.png": "Curved Delicate Delicate",
    "nose_09_01.png": "Curved Delicate Delicate",
    "nose_10_00.png": "Curved Medium Balanced",
    "nose_11_00.png": "Curved Wide Substantial",
    "nose_12_00.png": "Curved Strong Prominent",
    "nose_12_01.png": "Curved Strong Distinctive",
    "nose_20_00.png": "Straight Bridge Defined",
    "nose_21_00.png": "Strong Bridge Masculine"
  },
  "3_Accessory_Accessory": {
    "accessory_00_00.png": "Beauty Mark Black",
    "accessory_00_01.png": "Beauty Mark Black",
    "accessory_00_02.png": "Beauty Mark Black",
    "accessory_00_03.png": "Beauty Mark Black",
    "accessory_01_00.png": "Monocle Black",
    "accessory_02_00.png": "Round Glasses Black",
    "accessory_02_01.png": "Round Glasses Black",
    "accessory_02_02.png": "Round Glasses Black",
    "accessory_02_03.png": "Rectangular Glasses Black",
    "accessory_03_00.png": "Smoking Pipe Black"
  },
  "4_Eyebrows_Hair": {
    "eyebrows_00_00.png": "Curved Natural Black",
    "eyebrows_00_01.png": "Curved Natural Black",
    "eyebrows_01_00.png": "Straight Thin Black",
    "eyebrows_02_00.png": "Straight Medium Black",
    "eyebrows_02_01.png": "Straight Medium Black",
    "eyebrows_03_00.png": "Curved Thick Black",
    "eyebrows_03_01.png": "Curved Thick Black",
    "eyebrows_04_00.png": "Angled Thick Black",
    "eyebrows_05_00.png": "Straight Flat Black",
    "eyebrows_05_01.png": "Straight Flat Thick Black",
    "eyebrows_05_02.png": "Straight Flat Black",
    "eyebrows_06_00.png": "Curved Angular Black",
    "eyebrows_06_01.png": "Curved Angular Black",
    "eyebrows_07_00.png": "Unibrow Black"
  },
  "5_Eyes_Eye": {
    "eyes_00_00.png": "Closed Neutral Black",
    "eyes_00_01.png": "Squinting Happy Black",
    "eyes_01_00.png": "Closed Neutral Black",
    "eyes_02_00.png": "Closed Neutral Black",
    "eyes_03_00.png": "Narrow Squint Black",
    "eyes_03_01.png": "Alert Narrow Black",
    "eyes_03_02.png": "Squinting Closed Black",
    "eyes_03_03.png": "Arched Squint Black",
    "eyes_03_04.png": "Determined Squint Black",
    "eyes_03_05.png": "Angry Squint Black",
    "eyes_04_00.png": "Closed Blank Transparent",
    "eyes_04_01.png": "Sleepy Half-Closed Black",
    "eyes_05_00.png": "Narrow Slits Black",
    "eyes_06_00.png": "Narrow Slits Black",
    "eyes_07_00.png": "Narrow Slits Black",
    "eyes_07_01.png": "Alert Narrow Black",
    "eyes_08_00.png": "Solid Dots Black",
    "eyes_08_01.png": "Angry Narrow Black",
    "eyes_08_02.png": "Closed Blank Blank",
    "eyes_08_03.png": "Downcast Narrow Black",
    "eyes_09_00.png": "Small Dots Black",
    "eyes_09_00_female.png": "Feminine Almond Black",
    "eyes_09_01.png": "Small Dots Black",
    "eyes_09_01_female.png": "Feminine Almond Black",
    "eyes_10_00.png": "Winking Asymmetric Black",
    "eyes_11_00.png": "Wide Open Solid Black",
    "eyes_12_00.png": "Curved Relaxed Black",
    "eyes_12_01.png": "Curved Relaxed Black"
  },
  "6_HeadshapeAuxiliary_Skin": {
    "headshape_00_00.png": "Chin Shadow Skin Tone",
    "headshape_01_00.png": "Jaw Definition Skin Tone"
  },
  "7_Moustache_Hair": {
    "moustache_00_00.png": "Toothbrush Style Black",
    "moustache_00_01.png": "Pencil Thin Black",
    "moustache_01_00.png": "Handlebar Wide Black",
    "moustache_01_01.png": "Handlebar Black",
    "moustache_02_00.png": "Chevron Thick Black",
    "moustache_02_01.png": "Chevron Black",
    "moustache_03_00.png": "Walrus Layered Black",
    "moustache_03_01.png": "Walrus Black",
    "moustache_03_02.png": "Walrus Full Black",
    "moustache_04_00.png": "Pyramidal Black",
    "moustache_04_01.png": "Pyramidal Black",
    "moustache_04_02.png": "Pyramidal Full Black"
  },
  "8_Beard_Hair": {
    "beard_00_00.png": "Full Round Beard Black",
    "beard_00_01.png": "Full Beard Black",
    "beard_00_02.png": "Full Dense Beard Black",
    "beard_20_00.png": "Goatee Pointed Black"
  },
  "9_Mouth_Lip": {
    "mouth_00_00.png": "Neutral Closed Black",
    "mouth_01_00.png": "Slightly Parted Black",
    "mouth_02_00.png": "Pursed Black",
    "mouth_03_00.png": "Slight Curve Black",
    "mouth_04_00.png": "Flat Line Black",
    "mouth_05_00.png": "Downturned Black",
    "mouth_06_00.png": "Wide Smile Black",
    "mouth_07_00.png": "Open Smile Black",
    "mouth_08_00.png": "Smirk Black",
    "mouth_09_00.png": "Gentle Smile Black",
    "mouth_10_00.png": "Compressed Black",
    "mouth_11_00.png": "Open Round Black",
    "mouth_12_00.png": "Wide Open Black",
    "mouth_13_00.png": "Small Open Black",
    "mouth_14_00.png": "Slight Frown Black",
    "mouth_15_00.png": "Wavy Smile Black"
  },
  "10_Hair_Hair": {
    "hair_00_00.png": "Spiky Short Black",
    "hair_00_01.png": "Spiky Short Lighter Tone",
    "hair_00_02.png": "Spiky Short Medium Tone",
    "hair_01_00.png": "Swept Side Black",
    "hair_01_01.png": "Swept Side Lighter Tone",
    "hair_02_00.png": "Buzzcut Short Black",
    "hair_02_01.png": "Buzzcut Short Medium Tone",
    "hair_02_02.png": "Buzzcut Short Lighter Tone",
    "hair_03_00.png": "Side Part Slicked Black",
    "hair_03_01.png": "Side Part Slicked Medium",
    "hair_03_02.png": "Side Part Slicked Light",
    "hair_04_00.png": "Bald Bald",
    "hair_05_00.png": "Receding Short Black",
    "hair_05_01.png": "Receding Short Medium Tone",
    "hair_06_00.png": "Wavy Medium Black",
    "hair_06_01.png": "Wavy Medium Medium Tone",
    "hair_06_02.png": "Wavy Medium Light Tone",
    "hair_07_00.png": "Long Flowing Black",
    "hair_07_00_female.png": "Long Wavy Feminine Black",
    "hair_07_01.png": "Long Flowing Medium Tone",
    "hair_07_01_female.png": "Long Wavy Feminine Brown",
    "hair_07_02_female.png": "Long Wavy Updo Medium",
    "hair_07_03_female.png": "Long Wavy Flowing Medium",
    "hair_08_00.png": "Bob Short Black",
    "hair_08_00_female.png": "Curly Bob Black",
    "hair_08_01.png": "Bob Short Medium Tone",
    "hair_08_01_female.png": "Curly Bob Brown",
    "hair_09_00.png": "Ponytail Side Black",
    "hair_09_00_female.png": "Twin Tails Curly Black",
    "hair_09_01.png": "Ponytail Side Medium Tone",
    "hair_09_01_female.png": "Swept Wavy Side Brown",
    "hair_09_02_female.png": "Curly Updo Medium Tone",
    "hair_09_03_female.png": "Side Bun Medium Tone",
    "hair_10_00.png": "Wavy Long Black",
    "hair_10_00_female.png": "Wavy Shoulder-Length Black",
    "hair_10_01.png": "Wavy Long Medium Tone",
    "hair_10_01_female.png": "Wavy Shoulder-Length Brown",
    "hair_11_00.png": "Wavy Bob Black",
    "hair_11_01.png": "Wavy Bob Medium Tone",
    "hair_12_00.png": "Curly Bob Black",
    "hair_13_00.png": "Curly Afro Black"
  },
  "11_Detail_Skin": {
    "detail_00_00.png": "Forehead Wrinkle Skin Shadow",
    "detail_01_00.png": "Worry Lines Skin Shadow",
    "detail_02_00.png": "Frown Line Skin Shadow",
    "detail_03_00.png": "Frown Lines Skin Shadow",
    "detail_04_00.png": "Combination Lines Skin Shadow",
    "detail_05_00.png": "Crow'S Feet Skin Shadow",
    "detail_06_00.png": "Under Eye Shadow Skin",
    "detail_07_00.png": "Cheek Line Skin Shadow",
    "detail_08_00.png": "Deep Smile Lines Skin",
    "detail_09_00.png": "Jaw Shadow Skin Shadow"
  },
  "12_Detail_Skin": {
    "detail_10_00.png": "Cheek Blush Skin Tone",
    "detail_11_00.png": "Temple Shadow Skin Shadow",
    "detail_12_00.png": "Forehead Shadow Skin Shadow",
    "detail_13_00.png": "Bridge Shadow Skin Shadow",
    "detail_14_00.png": "Mouth Shadow Skin Shadow",
    "detail_15_00.png": "Neck Shadow Skin Shadow",
    "detail_16_00.png": "Chin Shadow Skin Shadow",
    "detail_17_00.png": "Overall Shading Skin Shadow",
    "detail_18_00.png": "Side Shadow Skin Shadow",
    "detail_19_00.png": "Eye Socket Shadow Skin",
    "detail_20_00.png": "Brow Shadow Skin Shadow"
  },
  "13_Headshape_Skin": {
    "headshape_00_00.png": "Oval Standard Neutral",
    "headshape_00_01.png": "Oval Standard Balanced",
    "headshape_01_00.png": "Round Soft Youthful",
    "headshape_02_00.png": "Angular Square Masculine",
    "headshape_03_00.png": "Heart Shaped Feminine",
    "headshape_04_00.png": "Diamond Angular Distinctive",
    "headshape_05_00.png": "Rectangular Long Elongated",
    "headshape_06_00.png": "Triangular Strong Strong Jaw",
    "headshape_07_00.png": "Narrow Oval Delicate",
    "headshape_07_01.png": "Narrow Oval Refined",
    "headshape_08_00.png": "Broad Square Very Masculine",
    "headshape_08_00_female.png": "Soft Oval Feminine Feminine",
    "headshape_08_01.png": "Broad Square Very Masculine",
    "headshape_08_01_female.png": "Soft Oval Feminine Feminine",
    "headshape_08_02.png": "Broad Square Masculine",
    "headshape_09_00.png": "Round Full Youthful",
    "headshape_09_00_female.png": "Round Soft Feminine Feminine",
    "headshape_09_01.png": "Round Full Very Youthful",
    "headshape_09_01_female.png": "Round Soft Feminine Feminine",
    "headshape_10_00.png": "Soft Standard Neutral",
    "headshape_11_00.png": "Soft Oval Gentle",
    "headshape_12_00.png": "Standard Balanced Neutral",
    "headshape_13_00.png": "Rounded Standard Neutral",
    "headshape_14_00.png": "Oval Mature Mature",
    "headshape_15_00.png": "Standard Neutral Neutral"
  },
  "15_Ears_Skin": {
    "ears_00_00.png": "Standard Rounded Normal",
    "ears_01_00.png": "Small Compact Small",
    "ears_02_00.png": "Large Prominent Large",
    "ears_03_00.png": "Angular Pointed Angular",
    "ears_04_00.png": "Round Full Rounded",
    "ears_05_00.png": "Narrow Elongated Long",
    "ears_06_00.png": "Flat Close Flat",
    "ears_07_00.png": "Detached Lobes Distinctive Lobes"
  },
  "16_Clothes_Clothes": {
    "clothes_00_00.png": "Formal Suit Dark Blue",
    "clothes_00_01.png": "Formal Suit Dark With",
    "clothes_01_00.png": "Aircrew Outfit",
    "clothes_02_00.png": "Cook Outfit",
    "clothes_03_00.png": "Field Mechanic Outfit",
    "clothes_04_00.png": "Field Engineer Outfit",
    "clothes_05_00.png": "RAF Medic Outfit",
    "clothes_06_00.png": "AAF Labour Outfit",
    "clothes_07_00_F.png": "AAF Cook Outfit (Female)",
    "clothes_08_00_F.png": "Field Engineer Outfit (Female)",
    "clothes_09_00_F.png": "AAF Labour Outfit (Female)",
    "clothes_10_00_F.png": "Field Mechanic Outfit (Female)",
    "clothes_11_00_F.png": "RAF Medic Outfit (Female)",
    "clothes_12_00_F.png": "Formal Suit (Female)"
  },
  "17_Body_Skin": {
    "body_00_00.png": "Neck And Shoulders Skin",
    "body_01_00.png": "Broad Shoulders Skin Tone"
  },
  "18_HairBack_Hair": {
    "hairback_04_00.png": "Bald Back Bald",
    "hairback_07_00_female.png": "Long Back Female Black",
    "hairback_07_01_female.png": "Long Back Female Brown",
    "hairback_07_03_female.png": "Long Back Female Light",
    "hairback_08_00.png": "Bob Back Black",
    "hairback_08_00_female.png": "Bob Back Female Black",
    "hairback_08_01.png": "Bob Back Medium Tone",
    "hairback_08_01_female.png": "Bob Back Female Brown",
    "hairback_09_00.png": "Ponytail Back Black",
    "hairback_09_00_female.png": "Ponytail Back Female Black",
    "hairback_09_01.png": "Ponytail Back Medium Tone",
    "hairback_09_01_female.png": "Ponytail Back Female Brown",
    "hairback_09_02.png": "Ponytail Back Light Tone",
    "hairback_09_02_female.png": "Ponytail Back Female Light",
    "hairback_09_03.png": "Side Ponytail Back Varied",
    "hairback_09_03_female.png": "Side Ponytail Back Female",
    "hairback_09_04_female.png": "Ponytail Back Female Varied",
    "hairback_09_05_female.png": "Ponytail Back Female Varied",
    "hairback_10_00.png": "Wavy Long Back Black",
    "hairback_10_00_female.png": "Wavy Long Back Female",
    "hairback_10_01.png": "Wavy Long Back Medium",
    "hairback_10_01_female.png": "Wavy Long Back Female Brown",
    "hairback_11_00.png": "Side Hair Strands Black",
    "hairback_11_01.png": "Side Hair Strands Medium",
    "hairback_12_00.png": "Side Curls Back Black",
    "hairback_12_01.png": "Side Curls Back Medium",
    "hairback_13_00.png": "Curly Sides Back Black"
  },
  "19_ClothesBack_Clothes": {
    "clothesback_00_00.png": "Suit Back Dark Formal",
    "clothesback_14_00.png": "Casual Back Varied"
  },
  "20_Background_Background": {
    "background_00_00.png": "Military Sunset Orange",
    "background_01_00.png": "Military Sunset Airfield Orange",
    "background_02_00.png": "Military Airfield Cloudy Blue",
    "background_03_00.png": "Military Hangar White"
  }
};
